// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ucMZM3jPAxBw_5SJZ4iRBY0lYjoFX7g',
    appId: '1:1051619785533:web:43e617359515cfc6652354',
    messagingSenderId: '1051619785533',
    projectId: 'smart-expense-6dd91',
    authDomain: 'smart-expense-6dd91.firebaseapp.com',
    storageBucket: 'smart-expense-6dd91.firebasestorage.app',
    measurementId: 'G-Q730773K8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOBcXOT5ckfG4pPehK8Gy6vH_zbR0nAU',
    appId: '1:1051619785533:android:24f41b5bfacf5d50652354',
    messagingSenderId: '1051619785533',
    projectId: 'smart-expense-6dd91',
    storageBucket: 'smart-expense-6dd91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7O1GKG6yvbtwIIxQ3RHeAf-u_gdOIz60',
    appId: '1:1051619785533:ios:0bc8a69e140f4125652354',
    messagingSenderId: '1051619785533',
    projectId: 'smart-expense-6dd91',
    storageBucket: 'smart-expense-6dd91.firebasestorage.app',
    iosClientId: '1051619785533-9voi36lpjda7eu9okp35kkcclqruh6lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7O1GKG6yvbtwIIxQ3RHeAf-u_gdOIz60',
    appId: '1:1051619785533:ios:0bc8a69e140f4125652354',
    messagingSenderId: '1051619785533',
    projectId: 'smart-expense-6dd91',
    storageBucket: 'smart-expense-6dd91.firebasestorage.app',
    iosClientId: '1051619785533-9voi36lpjda7eu9okp35kkcclqruh6lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ucMZM3jPAxBw_5SJZ4iRBY0lYjoFX7g',
    appId: '1:1051619785533:web:f7c7db1851df3127652354',
    messagingSenderId: '1051619785533',
    projectId: 'smart-expense-6dd91',
    authDomain: 'smart-expense-6dd91.firebaseapp.com',
    storageBucket: 'smart-expense-6dd91.firebasestorage.app',
    measurementId: 'G-Z4WK2PSQVF',
  );
}
